spring:
  application:
    name: spring-data-jpa-demo
  datasource:
    url: jdbc:mysql://localhost:3306/dao_demo_common_db
    username: demo.user
    password: 123456
    hikari:
      connection-timeout: 5000
      minimum-idle: 1
      maximum-pool-size: 3
      idle-timeout: 120000
  jpa:
    show-sql: true
    open-in-view: false
